version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: studybuddy_postgres
    environment:
      POSTGRES_DB: studybuddy
      POSTGRES_USER: studybuddy_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: studybuddy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@studybuddy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

