name: CI - Build & Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: studybuddy
          POSTGRES_PASSWORD: studybuddy
          POSTGRES_DB: studybuddydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U studybuddy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Debug system info
      - name: Debug system info
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          ./mvnw -v || echo "mvnw not executable"
          echo "Current directory:"
          pwd
          echo "List repo files:"
          ls -la

      # Step 4: Ensure mvnw is executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Step 5: Debug Postgres connectivity
      - name: Wait for Postgres & test connection
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U studybuddy; do
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "SELECT 1;" | psql -h localhost -U studybuddy -d studybuddydb

      # Step 6: Build with Maven (debug mode)
      - name: Build with Maven (debug logs)
        run: ./mvnw clean install -DskipTests=false -X
