name: CI - Build & Test (StudyBuddy)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: studybuddy
          POSTGRES_PASSWORD: studybuddy
          POSTGRES_DB: studybuddydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U studybuddy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Wait for Postgres & test connection
      - name: Wait for Postgres & verify connectivity
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          echo "Waiting for Postgres..."
          until pg_isready -h localhost -p 5432 -U studybuddy; do
            sleep 2
          done
          echo "Testing DB connection with SELECT 1..."
          PGPASSWORD=studybuddy psql -h localhost -U studybuddy -d studybuddydb -c "SELECT 1;"

      # 4. Make mvnw executable
      - name: Ensure mvnw is executable
        run: chmod +x mvnw

      # 5. Build with Maven (includes tests)
      - name: Run tests with CI config
        run: ./mvnw test -Dspring.config.name=application-ci

