name: CI - Build & Test (Maven + Spring Boot + PostgreSQL)

on:
  push:       # Run on every push
    branches: [ "main" ]
  pull_request:  # Also run on pull requests
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub runner environment

    services:
      postgres:              # Start a PostgreSQL service container
        image: postgres:15
        env:
          POSTGRES_USER: studybuddy
          POSTGRES_PASSWORD: studybuddy
          POSTGRES_DB: studybuddy
        ports:
          - 5432:5432
        options: >-           # Ensure DB is healthy before tests run
          --health-cmd="pg_isready -U studybuddy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven   # Cache Maven deps

      # 3. Ensure mvnw is executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # 4. Run Maven build + tests
      - name: Build & Test with Maven
        env:                # Pass DB connection info into Spring
          SPRING_PROFILES_ACTIVE: ci
        run: ./mvnw clean verify -B
