name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:   # <-- must be indented correctly
        image: postgres:14
        env:
          POSTGRES_DB: studybuddy
          POSTGRES_USER: studybuddy
          POSTGRES_PASSWORD: studybuddy
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U studybuddy -d studybuddy"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Ensure Maven wrapper is executable
        run: chmod +x mvnw

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U studybuddy; do
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Build & Test with Maven
        env:
          SPRING_PROFILES_ACTIVE: ci
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/studybuddy
          SPRING_DATASOURCE_USERNAME: studybuddy
          SPRING_DATASOURCE_PASSWORD: studybuddy
        run: ./mvnw clean verify -B
