name: CI - StudyBuddy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: studybuddy
          POSTGRES_PASSWORD: studybuddy
          POSTGRES_DB: studybuddy_db
        options: >-
          --health-cmd="pg_isready -U studybuddy -d studybuddy_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # ✅ Optional Debug Step: Verify DB connectivity before build
      - name: Wait for PostgreSQL and test connection
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          echo "Testing connection to Postgres..."
          PGPASSWORD=studybuddy psql -h localhost -U studybuddy -d studybuddy_db -c "SELECT 1;"

      # Step 3: Make Maven wrapper executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # Step 4: Build + run tests
      - name: Build with Maven (includes tests)
        run: ./mvnw clean install -DskipTests=false

